server.port=8083
spring.application.name=workflow-service

# Kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=workflow-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# Producer (Workflow -> status-changed)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer (Order -> created)  ? FIXED
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# JSON deserialize settings ? FIXED
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.tasreeh.po.workflow_service.events.OrderCreatedEvent


spring.kafka.producer.properties.spring.json.add.type.headers=false

# =============================
# OPENTELEMETRY TRACING
# =============================
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://otel-collector:4318/v1/traces
management.tracing.propagation.type=w3c
spring.kafka.template.observation-enabled=true
spring.kafka.listener.observation-enabled=true

# =============================
# GRACEFUL SHUTDOWN
# =============================
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
