server.port=8084
spring.application.name=notification-service

# Kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# ? Use ErrorHandlingDeserializer (prevents crash on bad message)
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# ? Ignore producer type headers (VERY IMPORTANT)
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ? Set your local event class package here (UPDATE if needed)
spring.kafka.consumer.properties.spring.json.value.default.type=com.tasreeh.po.notification_service.events.OrderStatusChangedEvent

# =============================
# OPENTELEMETRY TRACING
# =============================
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://otel-collector:4318/v1/traces
management.tracing.propagation.type=w3c
spring.kafka.listener.observation-enabled=true

# =============================
# GRACEFUL SHUTDOWN
# =============================
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
